---

package: plato.utilities.parser.parse_dstc2
class: Parser
arguments:
  data_path: ./ext_data/data/
  ontology: plato/example/domains/CamRestaurants-rules.json
  database: plato/example/domains/CamRestaurants-dbase.db
